# Generated by Django 5.0.5 on 2024-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_admin_keycloak", "0006_keycloakuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="keycloakprovider",
            name="app_name",
            field=models.CharField(blank=True, max_length=128, verbose_name="app name"),
        ),
    ]
