# Generated by Django 6.0.6 on 2026-07-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_keycloak', '0007_keycloakprovider_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakuser',
            name='family_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='last name'),
        ),
    ]
