# Generated by Django 6.0.6 on 2026-07-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_keycloak', '0008_alter_keycloakuser_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloaksession',
            name='sid',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='SID'),
        ),
    ]
